development:
  adapter: postgresql
  encoding: unicode
  database: InstagramHD_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: InstagramHD_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: InstagramHD_production
  pool: 5
  host: localhost